"""
AlarmUpdateDescriptor.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat


class AlarmUpdateDescriptor:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        AlarmUpdateDescriptor - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'alarm_ref': 'str',  # (required parameter)
            'alarm_control': 'str'
        }

        self.attribute_map = {
            'alarm_ref': 'alarmRef',  # (required parameter)
            'alarm_control': 'alarmControl'
        }

        self._alarm_ref = None
        self._alarm_control = None

    @property
    def alarm_ref(self):
        """
        Gets the alarm_ref of this AlarmUpdateDescriptor.
        The reference that identifies the physical alarm to modify.

        :return: The alarm_ref of this AlarmUpdateDescriptor.
        :rtype: str
        :required/optional: required
        """
        return self._alarm_ref

    @alarm_ref.setter
    def alarm_ref(self, alarm_ref):
        """
        Sets the alarm_ref of this AlarmUpdateDescriptor.
        The reference that identifies the physical alarm to modify.

        :param alarm_ref: The alarm_ref of this AlarmUpdateDescriptor.
        :type: str
        """
        self._alarm_ref = alarm_ref

    @property
    def alarm_control(self):
        """
        Gets the alarm_control of this AlarmUpdateDescriptor.
        Indicates the alarm control to activate on the specified alarm.

        :return: The alarm_control of this AlarmUpdateDescriptor.
        :rtype: str
        :required/optional: required
        """
        return self._alarm_control

    @alarm_control.setter
    def alarm_control(self, alarm_control):
        """
        Sets the alarm_control of this AlarmUpdateDescriptor.
        Indicates the alarm control to activate on the specified alarm.

        :param alarm_control: The alarm_control of this AlarmUpdateDescriptor.
        :type: str
        """
        allowed_values = ["enable", "disable", "mute", "refresh", "__UNDEFINED"]
        if alarm_control not in allowed_values:
            raise ValueError(
                "Invalid value for `alarm_control`, must be one of {}"
                .format(allowed_values)
            )
        self._alarm_control = alarm_control

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list([x.to_dict() if hasattr(x, "to_dict") else x for x in value])
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict([(item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item for item in list(value.items())])
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
           return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
