"""
ChannelPortParent.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat


class ChannelPortParent:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        """
        ChannelPortParent - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            "type": "str",  # (required parameter)
            "controller_ref": "str",
            "esm_ref": "str",
            "minihub_ref": "str",
            "hic_ref": "str",
        }

        self.attribute_map = {
            "type": "type",  # (required parameter)
            "controller_ref": "controllerRef",
            "esm_ref": "esmRef",
            "minihub_ref": "minihubRef",
            "hic_ref": "hicRef",
        }

        self._type = None
        self._controller_ref = None
        self._esm_ref = None
        self._minihub_ref = None
        self._hic_ref = None

    @property
    def type(self):
        """
        Gets the type of this ChannelPortParent.
        This enumeration object is used to specify the type of channel port parent.

        :return: The type of this ChannelPortParent.
        :rtype: str
        :required/optional: required
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ChannelPortParent.
        This enumeration object is used to specify the type of channel port parent.

        :param type: The type of this ChannelPortParent.
        :type: str
        """
        allowed_values = [
            "unknown",
            "esm",
            "minihub",
            "controller",
            "hic",
            "__UNDEFINED",
        ]
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type`, must be one of {}".format(allowed_values)
            )
        self._type = type

    @property
    def controller_ref(self):
        """
        Gets the controller_ref of this ChannelPortParent.
        This field is present only if the type field is equal to CHANNEL_PORT_PARENT_CONTROLLER.

        :return: The controller_ref of this ChannelPortParent.
        :rtype: str
        :required/optional: optional
        """
        return self._controller_ref

    @controller_ref.setter
    def controller_ref(self, controller_ref):
        """
        Sets the controller_ref of this ChannelPortParent.
        This field is present only if the type field is equal to CHANNEL_PORT_PARENT_CONTROLLER.

        :param controller_ref: The controller_ref of this ChannelPortParent.
        :type: str
        """
        self._controller_ref = controller_ref

    @property
    def esm_ref(self):
        """
        Gets the esm_ref of this ChannelPortParent.
        This field is present only if the type field is equal to CHANNEL_PORT_PARENT_ESM.

        :return: The esm_ref of this ChannelPortParent.
        :rtype: str
        :required/optional: optional
        """
        return self._esm_ref

    @esm_ref.setter
    def esm_ref(self, esm_ref):
        """
        Sets the esm_ref of this ChannelPortParent.
        This field is present only if the type field is equal to CHANNEL_PORT_PARENT_ESM.

        :param esm_ref: The esm_ref of this ChannelPortParent.
        :type: str
        """
        self._esm_ref = esm_ref

    @property
    def minihub_ref(self):
        """
        Gets the minihub_ref of this ChannelPortParent.
        This field is present only if the type field is equal to CHANNEL_PORT_PARENT_MINIHUB.

        :return: The minihub_ref of this ChannelPortParent.
        :rtype: str
        :required/optional: optional
        """
        return self._minihub_ref

    @minihub_ref.setter
    def minihub_ref(self, minihub_ref):
        """
        Sets the minihub_ref of this ChannelPortParent.
        This field is present only if the type field is equal to CHANNEL_PORT_PARENT_MINIHUB.

        :param minihub_ref: The minihub_ref of this ChannelPortParent.
        :type: str
        """
        self._minihub_ref = minihub_ref

    @property
    def hic_ref(self):
        """
        Gets the hic_ref of this ChannelPortParent.
        This field is present only if the type field is equal to CHANNEL_PORT_PARENT_HIC.

        :return: The hic_ref of this ChannelPortParent.
        :rtype: str
        :required/optional: optional
        """
        return self._hic_ref

    @hic_ref.setter
    def hic_ref(self, hic_ref):
        """
        Sets the hic_ref of this ChannelPortParent.
        This field is present only if the type field is equal to CHANNEL_PORT_PARENT_HIC.

        :param hic_ref: The hic_ref of this ChannelPortParent.
        :type: str
        """
        self._hic_ref = hic_ref

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    [
                        (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item
                        for item in list(value.items())
                    ]
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
            return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
