"""
DbmRecRetrieveStartDetails.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat


class DbmRecRetrieveStartDetails:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        """
        DbmRecRetrieveStartDetails - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            "skip_structure_integrity_check": "bool",  # (required parameter)
            "source_location": "str",  # (required parameter)
            "config_type": "str",
        }

        self.attribute_map = {
            "skip_structure_integrity_check": "skipStructureIntegrityCheck",  # (required parameter)
            "source_location": "sourceLocation",  # (required parameter)
            "config_type": "configType",
        }

        self._skip_structure_integrity_check = None
        self._source_location = None
        self._config_type = None

    @property
    def skip_structure_integrity_check(self):
        """
        Gets the skip_structure_integrity_check of this DbmRecRetrieveStartDetails.
        When true, the structure integrity check is skipped during the preparation phase of the data transfer.

        :return: The skip_structure_integrity_check of this DbmRecRetrieveStartDetails.
        :rtype: bool
        :required/optional: required
        """
        return self._skip_structure_integrity_check

    @skip_structure_integrity_check.setter
    def skip_structure_integrity_check(self, skip_structure_integrity_check):
        """
        Sets the skip_structure_integrity_check of this DbmRecRetrieveStartDetails.
        When true, the structure integrity check is skipped during the preparation phase of the data transfer.

        :param skip_structure_integrity_check: The skip_structure_integrity_check of this DbmRecRetrieveStartDetails.
        :type: bool
        """
        self._skip_structure_integrity_check = skip_structure_integrity_check

    @property
    def source_location(self):
        """
        Gets the source_location of this DbmRecRetrieveStartDetails.
        Defines which storage device to read the image from.

        :return: The source_location of this DbmRecRetrieveStartDetails.
        :rtype: str
        :required/optional: required
        """
        return self._source_location

    @source_location.setter
    def source_location(self, source_location):
        """
        Sets the source_location of this DbmRecRetrieveStartDetails.
        Defines which storage device to read the image from.

        :param source_location: The source_location of this DbmRecRetrieveStartDetails.
        :type: str
        """
        allowed_values = [
            "unknown",
            "dacstoreDisks",
            "onboardRpa",
            "hostImage",
            "__UNDEFINED",
        ]
        if source_location not in allowed_values:
            raise ValueError(
                "Invalid value for `source_location`, must be one of {}".format(
                    allowed_values
                )
            )
        self._source_location = source_location

    @property
    def config_type(self):
        """
        Gets the config_type of this DbmRecRetrieveStartDetails.
        Defines which set of record types to read.

        :return: The config_type of this DbmRecRetrieveStartDetails.
        :rtype: str
        :required/optional: required
        """
        return self._config_type

    @config_type.setter
    def config_type(self, config_type):
        """
        Sets the config_type of this DbmRecRetrieveStartDetails.
        Defines which set of record types to read.

        :param config_type: The config_type of this DbmRecRetrieveStartDetails.
        :type: str
        """
        allowed_values = [
            "configNone",
            "traditionalConfig",
            "configAll",
            "partialConfig",
            "__UNDEFINED",
        ]
        if config_type not in allowed_values:
            raise ValueError(
                "Invalid value for `config_type`, must be one of {}".format(
                    allowed_values
                )
            )
        self._config_type = config_type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    [
                        (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item
                        for item in list(value.items())
                    ]
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
            return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
