"""
DebugInfoExtent.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat
from six import iteritems


class DebugInfoExtent:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        DebugInfoExtent - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'controller': 'str',  # (required parameter)
            'handle': 'str',  # (required parameter)
            'chunk_number': 'int'
        }

        self.attribute_map = {
            'controller': 'controller',  # (required parameter)
            'handle': 'handle',  # (required parameter)
            'chunk_number': 'chunkNumber'
        }

        self._controller = None
        self._handle = None
        self._chunk_number = None

    @property
    def controller(self):
        """
        Gets the controller of this DebugInfoExtent.
        A reference to the controller from which the extent is requested.

        :return: The controller of this DebugInfoExtent.
        :rtype: str
        :required/optional: required
        """
        return self._controller

    @controller.setter
    def controller(self, controller):
        """
        Sets the controller of this DebugInfoExtent.
        A reference to the controller from which the extent is requested.

        :param controller: The controller of this DebugInfoExtent.
        :type: str
        """
        self._controller = controller

    @property
    def handle(self):
        """
        Gets the handle of this DebugInfoExtent.
        A controller-assigned identifier of a mutually-consistent collection of debug information extents. On the initial call (chunkNumber = 0), the handle is not significant.

        :return: The handle of this DebugInfoExtent.
        :rtype: str
        :required/optional: required
        """
        return self._handle

    @handle.setter
    def handle(self, handle):
        """
        Sets the handle of this DebugInfoExtent.
        A controller-assigned identifier of a mutually-consistent collection of debug information extents. On the initial call (chunkNumber = 0), the handle is not significant.

        :param handle: The handle of this DebugInfoExtent.
        :type: str
        """
        self._handle = handle

    @property
    def chunk_number(self):
        """
        Gets the chunk_number of this DebugInfoExtent.
        The number of the \"chunk\" of debug information to return. Note that chunk number zero has special significance - see structure DebugInfo.

        :return: The chunk_number of this DebugInfoExtent.
        :rtype: int
        :required/optional: required
        """
        return self._chunk_number

    @chunk_number.setter
    def chunk_number(self, chunk_number):
        """
        Sets the chunk_number of this DebugInfoExtent.
        The number of the \"chunk\" of debug information to return. Note that chunk number zero has special significance - see structure DebugInfo.

        :param chunk_number: The chunk_number of this DebugInfoExtent.
        :type: int
        """
        self._chunk_number = chunk_number

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list([x.to_dict() if hasattr(x, "to_dict") else x for x in value])
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict([(item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item for item in list(value.items())])
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
           return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

