"""
EnergyStarData.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat


class EnergyStarData:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        """
        EnergyStarData - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            "total_power": "int",  # (required parameter)
            "number_of_trays": "int",  # (required parameter)
            "tray_power": "list[TrayPower]",
        }

        self.attribute_map = {
            "total_power": "totalPower",  # (required parameter)
            "number_of_trays": "numberOfTrays",  # (required parameter)
            "tray_power": "trayPower",
        }

        self._total_power = None
        self._number_of_trays = None
        self._tray_power = None

    @property
    def total_power(self):
        """
        Gets the total_power of this EnergyStarData.
        The total measured power drawn by the array measured in watts.

        :return: The total_power of this EnergyStarData.
        :rtype: int
        :required/optional: required
        """
        return self._total_power

    @total_power.setter
    def total_power(self, total_power):
        """
        Sets the total_power of this EnergyStarData.
        The total measured power drawn by the array measured in watts.

        :param total_power: The total_power of this EnergyStarData.
        :type: int
        """
        self._total_power = total_power

    @property
    def number_of_trays(self):
        """
        Gets the number_of_trays of this EnergyStarData.
        The number of trays reporting power data.

        :return: The number_of_trays of this EnergyStarData.
        :rtype: int
        :required/optional: required
        """
        return self._number_of_trays

    @number_of_trays.setter
    def number_of_trays(self, number_of_trays):
        """
        Sets the number_of_trays of this EnergyStarData.
        The number of trays reporting power data.

        :param number_of_trays: The number_of_trays of this EnergyStarData.
        :type: int
        """
        self._number_of_trays = number_of_trays

    @property
    def tray_power(self):
        """
        Gets the tray_power of this EnergyStarData.
        List of power data by tray.

        :return: The tray_power of this EnergyStarData.
        :rtype: list[TrayPower]
        :required/optional: required
        """
        return self._tray_power

    @tray_power.setter
    def tray_power(self, tray_power):
        """
        Sets the tray_power of this EnergyStarData.
        List of power data by tray.

        :param tray_power: The tray_power of this EnergyStarData.
        :type: list[TrayPower]
        """
        self._tray_power = tray_power

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    [
                        (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item
                        for item in list(value.items())
                    ]
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
            return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
