"""
HistogramSummary.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat
from six import iteritems


class HistogramSummary:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        HistogramSummary - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'total_samples': 'int',  # (required parameter)
            'sum_samples': 'int',  # (required parameter)
            'min_sample': 'int',  # (required parameter)
            'max_sample': 'int'
        }

        self.attribute_map = {
            'total_samples': 'totalSamples',  # (required parameter)
            'sum_samples': 'sumSamples',  # (required parameter)
            'min_sample': 'minSample',  # (required parameter)
            'max_sample': 'maxSample'
        }

        self._total_samples = None
        self._sum_samples = None
        self._min_sample = None
        self._max_sample = None

    @property
    def total_samples(self):
        """
        Gets the total_samples of this HistogramSummary.
        The total number of samples.

        :return: The total_samples of this HistogramSummary.
        :rtype: int
        :required/optional: required
        """
        return self._total_samples

    @total_samples.setter
    def total_samples(self, total_samples):
        """
        Sets the total_samples of this HistogramSummary.
        The total number of samples.

        :param total_samples: The total_samples of this HistogramSummary.
        :type: int
        """
        self._total_samples = total_samples

    @property
    def sum_samples(self):
        """
        Gets the sum_samples of this HistogramSummary.
        The sum of all samples.

        :return: The sum_samples of this HistogramSummary.
        :rtype: int
        :required/optional: required
        """
        return self._sum_samples

    @sum_samples.setter
    def sum_samples(self, sum_samples):
        """
        Sets the sum_samples of this HistogramSummary.
        The sum of all samples.

        :param sum_samples: The sum_samples of this HistogramSummary.
        :type: int
        """
        self._sum_samples = sum_samples

    @property
    def min_sample(self):
        """
        Gets the min_sample of this HistogramSummary.
        The minimum sampled value.

        :return: The min_sample of this HistogramSummary.
        :rtype: int
        :required/optional: required
        """
        return self._min_sample

    @min_sample.setter
    def min_sample(self, min_sample):
        """
        Sets the min_sample of this HistogramSummary.
        The minimum sampled value.

        :param min_sample: The min_sample of this HistogramSummary.
        :type: int
        """
        self._min_sample = min_sample

    @property
    def max_sample(self):
        """
        Gets the max_sample of this HistogramSummary.
        The maximum sampled value.

        :return: The max_sample of this HistogramSummary.
        :rtype: int
        :required/optional: required
        """
        return self._max_sample

    @max_sample.setter
    def max_sample(self, max_sample):
        """
        Sets the max_sample of this HistogramSummary.
        The maximum sampled value.

        :param max_sample: The max_sample of this HistogramSummary.
        :type: int
        """
        self._max_sample = max_sample

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list([x.to_dict() if hasattr(x, "to_dict") else x for x in value])
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict([(item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item for item in list(value.items())])
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
           return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

