"""
HostPortChangeableProperties.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat


class HostPortChangeableProperties:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        HostPortChangeableProperties - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'host_port_name': 'list[str]',  # (required parameter)
            'label': 'list[str]',  # (required parameter)
            'host_ref': 'list[str]'
        }

        self.attribute_map = {
            'host_port_name': 'hostPortName',  # (required parameter)
            'label': 'label',  # (required parameter)
            'host_ref': 'hostRef'
        }

        self._host_port_name = None
        self._label = None
        self._host_ref = None

    @property
    def host_port_name(self):
        """
        Gets the host_port_name of this HostPortChangeableProperties.
        The unique, externally-defined identifier for this object. For example, for a Fibre Channel host port, this field contains the value of the Fibre Channel world-wide name for the port.

        :return: The host_port_name of this HostPortChangeableProperties.
        :rtype: list[str]
        :required/optional: required
        """
        return self._host_port_name

    @host_port_name.setter
    def host_port_name(self, host_port_name):
        """
        Sets the host_port_name of this HostPortChangeableProperties.
        The unique, externally-defined identifier for this object. For example, for a Fibre Channel host port, this field contains the value of the Fibre Channel world-wide name for the port.

        :param host_port_name: The host_port_name of this HostPortChangeableProperties.
        :type: list[str]
        """
        self._host_port_name = host_port_name

    @property
    def label(self):
        """
        Gets the label of this HostPortChangeableProperties.
        The user-assigned, descriptive label string for the host port.

        :return: The label of this HostPortChangeableProperties.
        :rtype: list[str]
        :required/optional: required
        """
        return self._label

    @label.setter
    def label(self, label):
        """
        Sets the label of this HostPortChangeableProperties.
        The user-assigned, descriptive label string for the host port.

        :param label: The label of this HostPortChangeableProperties.
        :type: list[str]
        """
        self._label = label

    @property
    def host_ref(self):
        """
        Gets the host_ref of this HostPortChangeableProperties.
        The host reference value of the host in which this port resides.

        :return: The host_ref of this HostPortChangeableProperties.
        :rtype: list[str]
        :required/optional: required
        """
        return self._host_ref

    @host_ref.setter
    def host_ref(self, host_ref):
        """
        Sets the host_ref of this HostPortChangeableProperties.
        The host reference value of the host in which this port resides.

        :param host_ref: The host_ref of this HostPortChangeableProperties.
        :type: list[str]
        """
        self._host_ref = host_ref

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list([x.to_dict() if hasattr(x, "to_dict") else x for x in value])
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict([(item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item for item in list(value.items())])
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
           return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
