"""
KeyValueTagMapping.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat


class KeyValueTagMapping:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        KeyValueTagMapping - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'key_value_tag_ref': 'str',  # (required parameter)
            'associated_object': 'KeyValueTagObjectReference',  # (required parameter)
            'mapping_ref': 'str'
        }

        self.attribute_map = {
            'key_value_tag_ref': 'keyValueTagRef',  # (required parameter)
            'associated_object': 'associatedObject',  # (required parameter)
            'mapping_ref': 'mappingRef'
        }

        self._key_value_tag_ref = None
        self._associated_object = None
        self._mapping_ref = None

    @property
    def key_value_tag_ref(self):
        """
        Gets the key_value_tag_ref of this KeyValueTagMapping.
        This field identifies the key-value tag to be associated with the Volume or Workload.

        :return: The key_value_tag_ref of this KeyValueTagMapping.
        :rtype: str
        :required/optional: required
        """
        return self._key_value_tag_ref

    @key_value_tag_ref.setter
    def key_value_tag_ref(self, key_value_tag_ref):
        """
        Sets the key_value_tag_ref of this KeyValueTagMapping.
        This field identifies the key-value tag to be associated with the Volume or Workload.

        :param key_value_tag_ref: The key_value_tag_ref of this KeyValueTagMapping.
        :type: str
        """
        self._key_value_tag_ref = key_value_tag_ref

    @property
    def associated_object(self):
        """
        Gets the associated_object of this KeyValueTagMapping.
        This element identifies the object that is associated with the key-value tag.

        :return: The associated_object of this KeyValueTagMapping.
        :rtype: KeyValueTagObjectReference
        :required/optional: required
        """
        return self._associated_object

    @associated_object.setter
    def associated_object(self, associated_object):
        """
        Sets the associated_object of this KeyValueTagMapping.
        This element identifies the object that is associated with the key-value tag.

        :param associated_object: The associated_object of this KeyValueTagMapping.
        :type: KeyValueTagObjectReference
        """
        self._associated_object = associated_object

    @property
    def mapping_ref(self):
        """
        Gets the mapping_ref of this KeyValueTagMapping.
        The unique identifier for the specific mapping between the KeyValueTag and the KeyValueTagObjectReference identified in this structure.

        :return: The mapping_ref of this KeyValueTagMapping.
        :rtype: str
        :required/optional: required
        """
        return self._mapping_ref

    @mapping_ref.setter
    def mapping_ref(self, mapping_ref):
        """
        Sets the mapping_ref of this KeyValueTagMapping.
        The unique identifier for the specific mapping between the KeyValueTag and the KeyValueTagObjectReference identified in this structure.

        :param mapping_ref: The mapping_ref of this KeyValueTagMapping.
        :type: str
        """
        self._mapping_ref = mapping_ref

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list([x.to_dict() if hasattr(x, "to_dict") else x for x in value])
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict([(item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item for item in list(value.items())])
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
           return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
