"""
TrayPower.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat
from six import iteritems


class TrayPower:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        TrayPower - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'tray_id': 'int',  # (required parameter)
            'number_of_power_supplies': 'int',  # (required parameter)
            'input_power': 'list[int]'
        }

        self.attribute_map = {
            'tray_id': 'trayID',  # (required parameter)
            'number_of_power_supplies': 'numberOfPowerSupplies',  # (required parameter)
            'input_power': 'inputPower'
        }

        self._tray_id = None
        self._number_of_power_supplies = None
        self._input_power = None

    @property
    def tray_id(self):
        """
        Gets the tray_id of this TrayPower.
        The tray ID.

        :return: The tray_id of this TrayPower.
        :rtype: int
        :required/optional: required
        """
        return self._tray_id

    @tray_id.setter
    def tray_id(self, tray_id):
        """
        Sets the tray_id of this TrayPower.
        The tray ID.

        :param tray_id: The tray_id of this TrayPower.
        :type: int
        """
        self._tray_id = tray_id

    @property
    def number_of_power_supplies(self):
        """
        Gets the number_of_power_supplies of this TrayPower.
        The number of power supplies in the tray.

        :return: The number_of_power_supplies of this TrayPower.
        :rtype: int
        :required/optional: required
        """
        return self._number_of_power_supplies

    @number_of_power_supplies.setter
    def number_of_power_supplies(self, number_of_power_supplies):
        """
        Sets the number_of_power_supplies of this TrayPower.
        The number of power supplies in the tray.

        :param number_of_power_supplies: The number_of_power_supplies of this TrayPower.
        :type: int
        """
        self._number_of_power_supplies = number_of_power_supplies

    @property
    def input_power(self):
        """
        Gets the input_power of this TrayPower.
        List of power measurements for each power supply measured in watts.

        :return: The input_power of this TrayPower.
        :rtype: list[int]
        :required/optional: required
        """
        return self._input_power

    @input_power.setter
    def input_power(self, input_power):
        """
        Sets the input_power of this TrayPower.
        List of power measurements for each power supply measured in watts.

        :param input_power: The input_power of this TrayPower.
        :type: list[int]
        """
        self._input_power = input_power

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list([x.to_dict() if hasattr(x, "to_dict") else x for x in value])
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict([(item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item for item in list(value.items())])
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
           return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

