"""
VolumeDeletionDescriptor.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat


class VolumeDeletionDescriptor:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        VolumeDeletionDescriptor - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'volume_ref': 'str',  # (required parameter)
            'delete_group_on_last_vol_deletion': 'bool'
        }

        self.attribute_map = {
            'volume_ref': 'volumeRef',  # (required parameter)
            'delete_group_on_last_vol_deletion': 'deleteGroupOnLastVolDeletion'
        }

        self._volume_ref = None
        self._delete_group_on_last_vol_deletion = None

    @property
    def volume_ref(self):
        """
        Gets the volume_ref of this VolumeDeletionDescriptor.
        A reference indicating which volume to delete.

        :return: The volume_ref of this VolumeDeletionDescriptor.
        :rtype: str
        :required/optional: required
        """
        return self._volume_ref

    @volume_ref.setter
    def volume_ref(self, volume_ref):
        """
        Sets the volume_ref of this VolumeDeletionDescriptor.
        A reference indicating which volume to delete.

        :param volume_ref: The volume_ref of this VolumeDeletionDescriptor.
        :type: str
        """
        self._volume_ref = volume_ref

    @property
    def delete_group_on_last_vol_deletion(self):
        """
        Gets the delete_group_on_last_vol_deletion of this VolumeDeletionDescriptor.
        An indication of how the procedure is to behave when the last volume in the group is deleted. If set to true, the volume group is also deleted; otherwise the volume group is retained.

        :return: The delete_group_on_last_vol_deletion of this VolumeDeletionDescriptor.
        :rtype: bool
        :required/optional: required
        """
        return self._delete_group_on_last_vol_deletion

    @delete_group_on_last_vol_deletion.setter
    def delete_group_on_last_vol_deletion(self, delete_group_on_last_vol_deletion):
        """
        Sets the delete_group_on_last_vol_deletion of this VolumeDeletionDescriptor.
        An indication of how the procedure is to behave when the last volume in the group is deleted. If set to true, the volume group is also deleted; otherwise the volume group is retained.

        :param delete_group_on_last_vol_deletion: The delete_group_on_last_vol_deletion of this VolumeDeletionDescriptor.
        :type: bool
        """
        self._delete_group_on_last_vol_deletion = delete_group_on_last_vol_deletion

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list([x.to_dict() if hasattr(x, "to_dict") else x for x in value])
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict([(item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item for item in list(value.items())])
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
           return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
