# import models into model package
from netapp.santricity.models.v2.access_volume_ex import AccessVolumeEx
from netapp.santricity.models.v2.add_batch_cg_members_request import AddBatchCGMembersRequest
from netapp.santricity.models.v2.add_consistency_group_member_request import AddConsistencyGroupMemberRequest
from netapp.santricity.models.v2.add_storage_system_return import AddStorageSystemReturn
from netapp.santricity.models.v2.alert_syslog_configuration import AlertSyslogConfiguration
from netapp.santricity.models.v2.alert_syslog_response import AlertSyslogResponse
from netapp.santricity.models.v2.alert_syslog_server import AlertSyslogServer
from netapp.santricity.models.v2.amg import Amg
from netapp.santricity.models.v2.amg_incomplete_member import AmgIncompleteMember
from netapp.santricity.models.v2.amg_member import AmgMember
from netapp.santricity.models.v2.analysed_controller_statistics import AnalysedControllerStatistics
from netapp.santricity.models.v2.analysed_disk_statistics import AnalysedDiskStatistics
from netapp.santricity.models.v2.analysed_storage_system_statistics import AnalysedStorageSystemStatistics
from netapp.santricity.models.v2.analysed_volume_statistics import AnalysedVolumeStatistics
from netapp.santricity.models.v2.analyzed_application_statistics import AnalyzedApplicationStatistics
from netapp.santricity.models.v2.analyzed_interface_statistics import AnalyzedInterfaceStatistics
from netapp.santricity.models.v2.analyzed_pool_statistics import AnalyzedPoolStatistics
from netapp.santricity.models.v2.analyzed_workload_statistics import AnalyzedWorkloadStatistics
from netapp.santricity.models.v2.application_statistics import ApplicationStatistics
from netapp.santricity.models.v2.asup_dispatch_request import AsupDispatchRequest
from netapp.santricity.models.v2.asup_entry import AsupEntry
from netapp.santricity.models.v2.asup_registration_request import AsupRegistrationRequest
from netapp.santricity.models.v2.asup_response import AsupResponse
from netapp.santricity.models.v2.asup_update_request import AsupUpdateRequest
from netapp.santricity.models.v2.async_communication_data import AsyncCommunicationData
from netapp.santricity.models.v2.async_mirror_connections_response import AsyncMirrorConnectionsResponse
from netapp.santricity.models.v2.async_mirror_group_connectivity_test_request import AsyncMirrorGroupConnectivityTestRequest
from netapp.santricity.models.v2.async_mirror_group_create_request import AsyncMirrorGroupCreateRequest
from netapp.santricity.models.v2.async_mirror_group_member_completion_request import AsyncMirrorGroupMemberCompletionRequest
from netapp.santricity.models.v2.async_mirror_group_member_create_request import AsyncMirrorGroupMemberCreateRequest
from netapp.santricity.models.v2.async_mirror_group_role_update_request import AsyncMirrorGroupRoleUpdateRequest
from netapp.santricity.models.v2.async_mirror_group_sync_request import AsyncMirrorGroupSyncRequest
from netapp.santricity.models.v2.async_mirror_group_update_request import AsyncMirrorGroupUpdateRequest
from netapp.santricity.models.v2.async_mirror_remote_connection import AsyncMirrorRemoteConnection
from netapp.santricity.models.v2.average_analysed_application_stats import AverageAnalysedApplicationStats
from netapp.santricity.models.v2.average_analysed_controller_stats import AverageAnalysedControllerStats
from netapp.santricity.models.v2.average_analysed_drive_stats import AverageAnalysedDriveStats
from netapp.santricity.models.v2.average_analysed_interface_stats import AverageAnalysedInterfaceStats
from netapp.santricity.models.v2.average_analysed_pool_stats import AverageAnalysedPoolStats
from netapp.santricity.models.v2.average_analysed_stats_response import AverageAnalysedStatsResponse
from netapp.santricity.models.v2.average_analysed_system_controller_stats import AverageAnalysedSystemControllerStats
from netapp.santricity.models.v2.average_analysed_system_stats import AverageAnalysedSystemStats
from netapp.santricity.models.v2.average_analysed_value import AverageAnalysedValue
from netapp.santricity.models.v2.average_analysed_volume_stats import AverageAnalysedVolumeStats
from netapp.santricity.models.v2.average_analysed_workload_stats import AverageAnalysedWorkloadStats
from netapp.santricity.models.v2.battery_ex import BatteryEx
from netapp.santricity.models.v2.cfw_package_metadata import CFWPackageMetadata
from netapp.santricity.models.v2.cg_snapshot_view_request import CGSnapshotViewRequest
from netapp.santricity.models.v2.cv_candidate_multiple_selection_request import CVCandidateMultipleSelectionRequest
from netapp.santricity.models.v2.cv_candidate_response import CVCandidateResponse
from netapp.santricity.models.v2.cv_candidate_selection_request import CVCandidateSelectionRequest
from netapp.santricity.models.v2.call_response import CallResponse
from netapp.santricity.models.v2.capabilities_response import CapabilitiesResponse
from netapp.santricity.models.v2.cfw_activation_request import CfwActivationRequest
from netapp.santricity.models.v2.cfw_upgrade_request import CfwUpgradeRequest
from netapp.santricity.models.v2.cfw_upgrade_response import CfwUpgradeResponse
from netapp.santricity.models.v2.concat_repository_volume import ConcatRepositoryVolume
from netapp.santricity.models.v2.concat_volume_candidate_request import ConcatVolumeCandidateRequest
from netapp.santricity.models.v2.concat_volume_expansion_request import ConcatVolumeExpansionRequest
from netapp.santricity.models.v2.configuration_db_validation_check import ConfigurationDbValidationCheck
from netapp.santricity.models.v2.configuration_result import ConfigurationResult
from netapp.santricity.models.v2.configuration_result_item import ConfigurationResultItem
from netapp.santricity.models.v2.consistency_group_create_request import ConsistencyGroupCreateRequest
from netapp.santricity.models.v2.consistency_group_update_request import ConsistencyGroupUpdateRequest
from netapp.santricity.models.v2.controller_stats import ControllerStats
from netapp.santricity.models.v2.create_cg_snapshot_view_manual_request import CreateCGSnapshotViewManualRequest
from netapp.santricity.models.v2.create_consistency_group_snapshot_request import CreateConsistencyGroupSnapshotRequest
from netapp.santricity.models.v2.create_consistency_group_snapshot_view_request import CreateConsistencyGroupSnapshotViewRequest
from netapp.santricity.models.v2.current_firmware_response import CurrentFirmwareResponse
from netapp.santricity.models.v2.device_alert_configuration import DeviceAlertConfiguration
from netapp.santricity.models.v2.device_alert_test_response import DeviceAlertTestResponse
from netapp.santricity.models.v2.device_asup_delivery import DeviceAsupDelivery
from netapp.santricity.models.v2.device_asup_device import DeviceAsupDevice
from netapp.santricity.models.v2.device_asup_response import DeviceAsupResponse
from netapp.santricity.models.v2.device_asup_schedule import DeviceAsupSchedule
from netapp.santricity.models.v2.device_asup_update_request import DeviceAsupUpdateRequest
from netapp.santricity.models.v2.device_asup_verify_request import DeviceAsupVerifyRequest
from netapp.santricity.models.v2.device_asup_verify_response import DeviceAsupVerifyResponse
from netapp.santricity.models.v2.device_data_response import DeviceDataResponse
from netapp.santricity.models.v2.diagnostic_data_request import DiagnosticDataRequest
from netapp.santricity.models.v2.discover_response import DiscoverResponse
from netapp.santricity.models.v2.discovered_storage_system import DiscoveredStorageSystem
from netapp.santricity.models.v2.discovery_start_request import DiscoveryStartRequest
from netapp.santricity.models.v2.disk_io_stats import DiskIOStats
from netapp.santricity.models.v2.disk_pool_priority_update_request import DiskPoolPriorityUpdateRequest
from netapp.santricity.models.v2.disk_pool_reduction_request import DiskPoolReductionRequest
from netapp.santricity.models.v2.disk_pool_threshold_update_request import DiskPoolThresholdUpdateRequest
from netapp.santricity.models.v2.drive_ex import DriveEx
from netapp.santricity.models.v2.drive_firmware_compatability_entry import DriveFirmwareCompatabilityEntry
from netapp.santricity.models.v2.drive_firmware_compatibility_response import DriveFirmwareCompatibilityResponse
from netapp.santricity.models.v2.drive_firmware_compatiblity_set import DriveFirmwareCompatiblitySet
from netapp.santricity.models.v2.drive_firmware_update_entry import DriveFirmwareUpdateEntry
from netapp.santricity.models.v2.drive_selection_request import DriveSelectionRequest
from netapp.santricity.models.v2.embedded_compatibility_check_response import EmbeddedCompatibilityCheckResponse
from netapp.santricity.models.v2.embedded_firmware_response import EmbeddedFirmwareResponse
from netapp.santricity.models.v2.enumeration_string import EnumerationString
from netapp.santricity.models.v2.esm_fibre_port_connection import EsmFibrePortConnection
from netapp.santricity.models.v2.esm_port_connection_response import EsmPortConnectionResponse
from netapp.santricity.models.v2.esm_sas_port_connection import EsmSasPortConnection
from netapp.santricity.models.v2.event import Event
from netapp.santricity.models.v2.event_object_identifier import EventObjectIdentifier
from netapp.santricity.models.v2.exclusive_operation_check import ExclusiveOperationCheck
from netapp.santricity.models.v2.failure_data import FailureData
from netapp.santricity.models.v2.fibre_interface_port import FibreInterfacePort
from netapp.santricity.models.v2.file_based_configuration_request import FileBasedConfigurationRequest
from netapp.santricity.models.v2.file_config_item import FileConfigItem
from netapp.santricity.models.v2.file_info import FileInfo
from netapp.santricity.models.v2.firmware_compatibility_request import FirmwareCompatibilityRequest
from netapp.santricity.models.v2.firmware_compatibility_response import FirmwareCompatibilityResponse
from netapp.santricity.models.v2.firmware_compatibility_set import FirmwareCompatibilitySet
from netapp.santricity.models.v2.firmware_upgrade_health_check_result import FirmwareUpgradeHealthCheckResult
from netapp.santricity.models.v2.flash_cache_create_request import FlashCacheCreateRequest
from netapp.santricity.models.v2.flash_cache_ex import FlashCacheEx
from netapp.santricity.models.v2.flash_cache_update_request import FlashCacheUpdateRequest
from netapp.santricity.models.v2.folder import Folder
from netapp.santricity.models.v2.folder_create_request import FolderCreateRequest
from netapp.santricity.models.v2.folder_event import FolderEvent
from netapp.santricity.models.v2.folder_update_request import FolderUpdateRequest
from netapp.santricity.models.v2.hardware_inventory_response import HardwareInventoryResponse
from netapp.santricity.models.v2.health_check_failure_response import HealthCheckFailureResponse
from netapp.santricity.models.v2.health_check_request import HealthCheckRequest
from netapp.santricity.models.v2.health_check_response import HealthCheckResponse
from netapp.santricity.models.v2.historical_stats_response import HistoricalStatsResponse
from netapp.santricity.models.v2.host_create_request import HostCreateRequest
from netapp.santricity.models.v2.host_ex import HostEx
from netapp.santricity.models.v2.host_group import HostGroup
from netapp.santricity.models.v2.host_group_create_request import HostGroupCreateRequest
from netapp.santricity.models.v2.host_group_update_request import HostGroupUpdateRequest
from netapp.santricity.models.v2.host_move_request import HostMoveRequest
from netapp.santricity.models.v2.host_port_create_request import HostPortCreateRequest
from netapp.santricity.models.v2.host_port_update_request import HostPortUpdateRequest
from netapp.santricity.models.v2.host_side_port import HostSidePort
from netapp.santricity.models.v2.host_type import HostType
from netapp.santricity.models.v2.host_type_values import HostTypeValues
from netapp.santricity.models.v2.host_update_request import HostUpdateRequest
from netapp.santricity.models.v2.ib_interface_port import IBInterfacePort
from netapp.santricity.models.v2.i_scsi_interface_port import IScsiInterfacePort
from netapp.santricity.models.v2.identification_request import IdentificationRequest
from netapp.santricity.models.v2.initial_async_response import InitialAsyncResponse
from netapp.santricity.models.v2.interface_stats import InterfaceStats
from netapp.santricity.models.v2.iom_service_info_response import IomServiceInfoResponse
from netapp.santricity.models.v2.iom_service_update_request import IomServiceUpdateRequest
from netapp.santricity.models.v2.iscsi_entity_response import IscsiEntityResponse
from netapp.santricity.models.v2.iscsi_entity_update_request import IscsiEntityUpdateRequest
from netapp.santricity.models.v2.iscsi_target_response import IscsiTargetResponse
from netapp.santricity.models.v2.iscsi_target_update_request import IscsiTargetUpdateRequest
from netapp.santricity.models.v2.job_progress import JobProgress
from netapp.santricity.models.v2.key_value import KeyValue
from netapp.santricity.models.v2.legacy_snapshot_create_request import LegacySnapshotCreateRequest
from netapp.santricity.models.v2.legacy_snapshot_ex import LegacySnapshotEx
from netapp.santricity.models.v2.legacy_snapshot_update_request import LegacySnapshotUpdateRequest
from netapp.santricity.models.v2.level import Level
from netapp.santricity.models.v2.locale import Locale
from netapp.santricity.models.v2.localized_log_message import LocalizedLogMessage
from netapp.santricity.models.v2.lockdown_status_response import LockdownStatusResponse
from netapp.santricity.models.v2.log_record import LogRecord
from netapp.santricity.models.v2.logger_record_response import LoggerRecordResponse
from netapp.santricity.models.v2.management_configuration_request import ManagementConfigurationRequest
from netapp.santricity.models.v2.management_interface import ManagementInterface
from netapp.santricity.models.v2.mappable_object import MappableObject
from netapp.santricity.models.v2.mel_entry_ex import MelEntryEx
from netapp.santricity.models.v2.mel_event_health_check import MelEventHealthCheck
from netapp.santricity.models.v2.metadata_change_event import MetadataChangeEvent
from netapp.santricity.models.v2.nvsram_package_metadata import NvsramPackageMetadata
from netapp.santricity.models.v2.object_change_event import ObjectChangeEvent
from netapp.santricity.models.v2.object_graph_change_event import ObjectGraphChangeEvent
from netapp.santricity.models.v2.object_graph_sync_check import ObjectGraphSyncCheck
from netapp.santricity.models.v2.operation_progress import OperationProgress
from netapp.santricity.models.v2.pitcg_member import PITCGMember
from netapp.santricity.models.v2.password_set_request import PasswordSetRequest
from netapp.santricity.models.v2.password_status_event import PasswordStatusEvent
from netapp.santricity.models.v2.password_status_response import PasswordStatusResponse
from netapp.santricity.models.v2.pit_view_ex import PitViewEx
from netapp.santricity.models.v2.pool_qos_response import PoolQosResponse
from netapp.santricity.models.v2.pool_statistics import PoolStatistics
from netapp.santricity.models.v2.progress import Progress
from netapp.santricity.models.v2.raid_migration_request import RaidMigrationRequest
from netapp.santricity.models.v2.raw_stats_response import RawStatsResponse
from netapp.santricity.models.v2.remote_candidate import RemoteCandidate
from netapp.santricity.models.v2.remote_communication_data import RemoteCommunicationData
from netapp.santricity.models.v2.remote_mirror_candidate import RemoteMirrorCandidate
from netapp.santricity.models.v2.remote_mirror_pair import RemoteMirrorPair
from netapp.santricity.models.v2.remote_volume_mirror_create_request import RemoteVolumeMirrorCreateRequest
from netapp.santricity.models.v2.remote_volume_mirror_update_request import RemoteVolumeMirrorUpdateRequest
from netapp.santricity.models.v2.removable_drive_response import RemovableDriveResponse
from netapp.santricity.models.v2.resource_bundle import ResourceBundle
from netapp.santricity.models.v2.rule import Rule
from netapp.santricity.models.v2.ssl_cert_configuration import SSLCertConfiguration
from netapp.santricity.models.v2.sas_interface_port import SasInterfacePort
from netapp.santricity.models.v2.save_config_spec import SaveConfigSpec
from netapp.santricity.models.v2.schedule_create_request import ScheduleCreateRequest
from netapp.santricity.models.v2.secure_volume_key_request import SecureVolumeKeyRequest
from netapp.santricity.models.v2.secure_volume_key_response import SecureVolumeKeyResponse
from netapp.santricity.models.v2.serializable import Serializable
from netapp.santricity.models.v2.single_number_value import SingleNumberValue
from netapp.santricity.models.v2.snapshot import Snapshot
from netapp.santricity.models.v2.snapshot_create_request import SnapshotCreateRequest
from netapp.santricity.models.v2.snapshot_group import SnapshotGroup
from netapp.santricity.models.v2.snapshot_group_create_request import SnapshotGroupCreateRequest
from netapp.santricity.models.v2.snapshot_group_update_request import SnapshotGroupUpdateRequest
from netapp.santricity.models.v2.snapshot_view_create_request import SnapshotViewCreateRequest
from netapp.santricity.models.v2.snapshot_view_update_request import SnapshotViewUpdateRequest
from netapp.santricity.models.v2.snapshot_volume_mode_conversion_request import SnapshotVolumeModeConversionRequest
from netapp.santricity.models.v2.software_version import SoftwareVersion
from netapp.santricity.models.v2.software_versions import SoftwareVersions
from netapp.santricity.models.v2.spm_database_health_check import SpmDatabaseHealthCheck
from netapp.santricity.models.v2.ssc_volume_create_request import SscVolumeCreateRequest
from netapp.santricity.models.v2.ssc_volume_update_request import SscVolumeUpdateRequest
from netapp.santricity.models.v2.stack_trace_element import StackTraceElement
from netapp.santricity.models.v2.staged_firmware_response import StagedFirmwareResponse
from netapp.santricity.models.v2.storage_device_health_check import StorageDeviceHealthCheck
from netapp.santricity.models.v2.storage_device_status_event import StorageDeviceStatusEvent
from netapp.santricity.models.v2.storage_pool_create_request import StoragePoolCreateRequest
from netapp.santricity.models.v2.storage_pool_expansion_request import StoragePoolExpansionRequest
from netapp.santricity.models.v2.storage_pool_update_request import StoragePoolUpdateRequest
from netapp.santricity.models.v2.storage_system_config_response import StorageSystemConfigResponse
from netapp.santricity.models.v2.storage_system_config_update_request import StorageSystemConfigUpdateRequest
from netapp.santricity.models.v2.storage_system_controller_stats import StorageSystemControllerStats
from netapp.santricity.models.v2.storage_system_create_request import StorageSystemCreateRequest
from netapp.santricity.models.v2.storage_system_response import StorageSystemResponse
from netapp.santricity.models.v2.storage_system_stats import StorageSystemStats
from netapp.santricity.models.v2.storage_system_update_request import StorageSystemUpdateRequest
from netapp.santricity.models.v2.subject_alternate_name import SubjectAlternateName
from netapp.santricity.models.v2.support_artifact import SupportArtifact
from netapp.santricity.models.v2.support_artifacts import SupportArtifacts
from netapp.santricity.models.v2.support_data_request import SupportDataRequest
from netapp.santricity.models.v2.support_data_response import SupportDataResponse
from netapp.santricity.models.v2.tag_event import TagEvent
from netapp.santricity.models.v2.thin_volume_cache_settings import ThinVolumeCacheSettings
from netapp.santricity.models.v2.thin_volume_create_request import ThinVolumeCreateRequest
from netapp.santricity.models.v2.thin_volume_ex import ThinVolumeEx
from netapp.santricity.models.v2.thin_volume_expansion_request import ThinVolumeExpansionRequest
from netapp.santricity.models.v2.thin_volume_update_request import ThinVolumeUpdateRequest
from netapp.santricity.models.v2.throwable import Throwable
from netapp.santricity.models.v2.trace_buffer_spec import TraceBufferSpec
from netapp.santricity.models.v2.tray_ex import TrayEx
from netapp.santricity.models.v2.unassociated_host_port import UnassociatedHostPort
from netapp.santricity.models.v2.unreadable_sector_entry_result import UnreadableSectorEntryResult
from netapp.santricity.models.v2.unreadable_sector_response import UnreadableSectorResponse
from netapp.santricity.models.v2.upgrade_manager_response import UpgradeManagerResponse
from netapp.santricity.models.v2.user_volume import UserVolume
from netapp.santricity.models.v2.validate_configuration_file_response_item import ValidateConfigurationFileResponseItem
from netapp.santricity.models.v2.validate_confiuration_file_response import ValidateConfiurationFileResponse
from netapp.santricity.models.v2.version_content import VersionContent
from netapp.santricity.models.v2.volume_action_progress_response import VolumeActionProgressResponse
from netapp.santricity.models.v2.volume_cache_settings import VolumeCacheSettings
from netapp.santricity.models.v2.volume_copy_create_request import VolumeCopyCreateRequest
from netapp.santricity.models.v2.volume_copy_pair import VolumeCopyPair
from netapp.santricity.models.v2.volume_copy_progress import VolumeCopyProgress
from netapp.santricity.models.v2.volume_copy_update_request import VolumeCopyUpdateRequest
from netapp.santricity.models.v2.volume_create_request import VolumeCreateRequest
from netapp.santricity.models.v2.volume_ex import VolumeEx
from netapp.santricity.models.v2.volume_expansion_request import VolumeExpansionRequest
from netapp.santricity.models.v2.volume_group_ex import VolumeGroupEx
from netapp.santricity.models.v2.volume_io_stats import VolumeIOStats
from netapp.santricity.models.v2.volume_mapping_create_request import VolumeMappingCreateRequest
from netapp.santricity.models.v2.volume_mapping_move_request import VolumeMappingMoveRequest
from netapp.santricity.models.v2.volume_metadata_item import VolumeMetadataItem
from netapp.santricity.models.v2.volume_update_request import VolumeUpdateRequest
from netapp.santricity.models.v2.workload_attribute import WorkloadAttribute
from netapp.santricity.models.v2.workload_copy_request import WorkloadCopyRequest
from netapp.santricity.models.v2.workload_create_request import WorkloadCreateRequest
from netapp.santricity.models.v2.workload_model import WorkloadModel
from netapp.santricity.models.v2.workload_statistics import WorkloadStatistics
from netapp.santricity.models.v2.workload_update_request import WorkloadUpdateRequest
from netapp.santricity.models.v2.x509_cert_info import X509CertInfo

