"""
CfwUpgradeRequest.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat
from six import iteritems


class CfwUpgradeRequest:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        CfwUpgradeRequest - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'cfw_file': 'str',  
            'nvsram_file': 'str',  
            'stage_firmware': 'bool',  
            'skip_mel_check': 'bool'
        }

        self.attribute_map = {
            'cfw_file': 'cfwFile',  
            'nvsram_file': 'nvsramFile',  
            'stage_firmware': 'stageFirmware',  
            'skip_mel_check': 'skipMelCheck'
        }

        self._cfw_file = None
        self._nvsram_file = None
        self._stage_firmware = None
        self._skip_mel_check = None

    @property
    def cfw_file(self):
        """
        Gets the cfw_file of this CfwUpgradeRequest.


        :return: The cfw_file of this CfwUpgradeRequest.
        :rtype: str
        :required/optional: optional
        """
        return self._cfw_file

    @cfw_file.setter
    def cfw_file(self, cfw_file):
        """
        Sets the cfw_file of this CfwUpgradeRequest.


        :param cfw_file: The cfw_file of this CfwUpgradeRequest.
        :type: str
        """
        self._cfw_file = cfw_file

    @property
    def nvsram_file(self):
        """
        Gets the nvsram_file of this CfwUpgradeRequest.


        :return: The nvsram_file of this CfwUpgradeRequest.
        :rtype: str
        :required/optional: optional
        """
        return self._nvsram_file

    @nvsram_file.setter
    def nvsram_file(self, nvsram_file):
        """
        Sets the nvsram_file of this CfwUpgradeRequest.


        :param nvsram_file: The nvsram_file of this CfwUpgradeRequest.
        :type: str
        """
        self._nvsram_file = nvsram_file

    @property
    def stage_firmware(self):
        """
        Gets the stage_firmware of this CfwUpgradeRequest.


        :return: The stage_firmware of this CfwUpgradeRequest.
        :rtype: bool
        :required/optional: optional
        """
        return self._stage_firmware

    @stage_firmware.setter
    def stage_firmware(self, stage_firmware):
        """
        Sets the stage_firmware of this CfwUpgradeRequest.


        :param stage_firmware: The stage_firmware of this CfwUpgradeRequest.
        :type: bool
        """
        self._stage_firmware = stage_firmware

    @property
    def skip_mel_check(self):
        """
        Gets the skip_mel_check of this CfwUpgradeRequest.
        Skip check of the MEL events for issues with the storage-system.

        :return: The skip_mel_check of this CfwUpgradeRequest.
        :rtype: bool
        :required/optional: optional
        """
        return self._skip_mel_check

    @skip_mel_check.setter
    def skip_mel_check(self, skip_mel_check):
        """
        Sets the skip_mel_check of this CfwUpgradeRequest.
        Skip check of the MEL events for issues with the storage-system.

        :param skip_mel_check: The skip_mel_check of this CfwUpgradeRequest.
        :type: bool
        """
        self._skip_mel_check = skip_mel_check

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list([x.to_dict() if hasattr(x, "to_dict") else x for x in value])
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict([(item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item for item in list(value.items())])
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
           return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

